# Site meta data
[site]
title = "rusty shutter"
author = "Linghua Zhang"

# Site navigation links
[[site.nav]]
icon = "assets/icons/home.svg"
link = "https://lhzhang.com"

[[site.nav]]
icon = "assets/icons/instagram.svg"
link = "https://instagram.com/o_lll"

[[site.nav]]
icon = "assets/icons/twitter.svg"
link = "https://twitter.com/o_lll"

# Setttings for photo size
[image]
thumbnailWidth = 640
originalWidth = 2048

# Layout for grids
[layout]
minColumn = 1
maxColumn = 4
minWidth = 200

# Photo sections
[[section]]
title = "rusty ones"
text = ""
slug = "rusty-ones"
folder = "photos/rusty-ones"

[[section]]
title = "the tired ones"
text = ""
slug = "tired-ones"
folder = "photos/tired-ones"

[[section]]
title = "the colorful world"
text = ""
slug = "colorful-ones"
folder = "photos/colorful-ones"

[others]
folders = [ "assets", "media", "CNAME" ]
show_foto_footer = true
