# docs: https://github.com/moulco/moul/tree/master/docs#example-moultoml
base = "/"
ga_measurement_id = ""

[style]
theme = "system-preference"
cover = "none"
content = "left"
photo_order = "descending"

[profile]
name = "Linghua Zhang"
bio = "Minimalist | Coder"

[social]
homepage = "https://lhzhang.com"
twitter = "o_lll"
github = "waynezhang"
instagram = "o_lll"
facebook = ""
youtube = ""

[content]
title = "rusty shutter"
text = ""

[section.1]
title = "the tired ones"
text = ""
